### ISSUE TITLE
Broken audio in Warframe

### ISSUE THREAD

**Issue by TLATER** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#10]
Audio in that game is completely missing with this proton version.

This appears to be fixed in the [latest release](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.21-GE-1), but it's marked as a "hotfix" - is it possible that release was force-pushed over the original release and the current Flathub version is therefore outdated?

I don't understand the versioning scheme of Proton-GE at all, frankly, sorry if this is not actually the problem.

**Comment by Lctrs** [comment]
Version `6.0-GE-1` is now available. Does it fix your issue ?

**Comment by TLATER** [comment]
Yes, it does! Can be closed from my point of view, if deploying that hotfix as a separate build isn't important :)

**Comment by Lctrs** [comment]
Thanks for your feedback. It's already available in the `stable` branch.
