### ISSUE TITLE
[Question] Is there a way to download your patched proton directly outside of Flathub

### ISSUE THREAD

**Issue by Vysp3r** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#129]
I want to know if it's possible to directly download your patched proton so that I can use it for my application. One user mentioned in https://github.com/Vysp3r/ProtonPlus/issues/63 that this proton version is the only one that works with gamescope for steam flatpak. (See this for reference: https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/7) 
I don't want my app to install a Flatpak addon and would rather have an archive file.

**Comment by Lctrs** [comment]
Out of the blue, I don't know a way to do this. I think you would have to mimick what's flatpak is doing to install a package from a repository.

**Comment by Vysp3r** [comment]
Alright, I think I'll just not do anything about that since spending time on mimicking would just be a waste of time in my book since not a lot of users use SteamFlatpak + GamescopeFlatpak.
