### ISSUE TITLE
Heroic launcher compatibility

### ISSUE THREAD

**Issue by AXL1994** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#170]
As stated in this [issue](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/309), the flatpak version of Proton-GE doesn't work for other application outside Steam. With the growing popularity of Heroic Launcher, is it possible to make it more app-agnostic to make it compatible with other apps?

**Comment by Lctrs** [comment]
As stated in the [official README](https://github.com/GloriousEggroll/proton-ge-custom#1-running-non-steam-games-with-proton-outside-of-steam-is-not-supported-do-not-ask-for-help-with-this), Proton-GE is only for steam games launched inside the Steam client.

For other launchers, you should use https://github.com/gloriouseggroll/wine-ge-custom, but it has not been flatpaked yet.
