### ISSUE TITLE
Update to latest version? (GE-Proton8-25)

### ISSUE THREAD

**Issue by bayazidbh** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#185]
Seems like there's [issue building since 8.17](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/pulls?q=) but I don't see much discussion about the build failures aside for a retry in #181, and we're almost a month behind in updates now.

Can I hear more details about the issues? I'm fine with waiting, but would like to hear about more details in the meantime.

**Comment by Lctrs** [comment]
Simple lack of time/motivation on my side. If someone wants to start working on fixing the build, feel free. It might just be a question of syncing changes from https://github.com/GloriousEggroll/proton-ge-custom/blob/master/Makefile.in in our build definitions.

**Comment by Sturmlocke86** [comment]
> Seems like there's [issue building since 8.17](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/pulls?q=) but I don't see much discussion about the build failures aside for a retry in #181, and we're almost a month behind in updates now.
> 
> Can I hear more details about the issues? I'm fine with waiting, but would like to hear about more details in the meantime.

+1. I currently use the Flatpak version of Steam and both the Proton community edition, which is stuck on Proton 7 atm, and the GEProton builds are outdated at this point. I need one of the two for gamescope / amd fsr / nvidia nis, so I've been waiting for a couple of months now. The current version of GEProton crashes in Forza 4, so an upgrade would be nice.  Is there any way to donate some cash to help ya'll? No rush ofc, it's alright if no1 can fix the community Flatpak builds. If all else fails I'll just move away from Flatpak for Steam and go with native by the end of next week.

Thanks!

**Comment by ChrisHobday** [comment]
Proton-GE has been updated to the latest version 9.10.
