### ISSUE TITLE
Cutscenes do not work in the Outer Worlds

### ISSUE THREAD

**Issue by nickavem** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#28]
Cutscenes do not work in The Outer Worlds for this version (com.valvesoftware.Steam.CompatibilityTool.Proton-GE 6.5-GE-3) but do work on RPM steam (Fedora 34) with [this version](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.8-GE-2). Both were tested with a fresh wine prefix.

When the cutscenes do not work (in flatpak) I get this instead:
![Screenshot from 2021-05-17 18-27-37](https://user-images.githubusercontent.com/72708798/118564565-88729c80-b73e-11eb-83d3-41dd36f3506d.png)

I have no clue as to why this is, and any help would be appreciated!

**Comment by Lctrs** [comment]
They probably fixed things in one of the later versions than 6.5-GE-3. Will try to find some time today to upgrade this flatpak.
