### ISSUE TITLE
Controller Patches Do Not Seem to Have an Effect on Origin Games

### ISSUE THREAD

**Issue by Saroufim** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#6]
According to [this](https://github.com/ValveSoftware/Proton/issues/4186) the Proton GE patches should allow controllers to be detected in EA games. However, with this branch of proton, it does not seem to be the case. I cannot get my dualshock 4 working with Dragon Age 2.

**Comment by gasinvein** [comment]
Does the controller work at all in Steam flatpak (i.e. in other games)?

**Comment by Saroufim** [comment]
I have the rules in place and yes it works swimmingly fine in non-Origin games (such as Skyrim, Overlord II, etc.)

**Comment by gasinvein** [comment]
Weird, then. Do you know what's the exact GE patch?

**Comment by Lctrs** [comment]
According to [this comment](https://github.com/ValveSoftware/Proton/issues/4186#issuecomment-701116561) on the linked issue, GE patches have no effect on Dragon Age.

**Comment by gasinvein** [comment]
@Lctrs Not sure about that. AFAIK DA2 and DAI have very different engines, so input system might work differently as well.

**Comment by Lctrs** [comment]
@Saroufim Could you test that it works on non-flatpak version then (Steam + Proton-GE) ?

**Comment by Saroufim** [comment]
Absolutely. I will report back the results

**Comment by Saroufim** [comment]
I'm facing another issue. Proton-GE-5.21-1 (non-flatpak) is not working with any games. After I finish troubleshooting this, I will report back.

**Comment by Lctrs** [comment]
Just in case, it won't work in the flatpaked Steam. You must run it with Steam running directly on the host.

**Comment by Saroufim** [comment]
I keep encountering pressure vessel errors. I think this is related to the "layered packages" feature of Fedora Silverblue.

**Comment by Saroufim** [comment]
I cannot reproduce this anymore. It seems a steam update fixed this. I will close this and if anyone experiences this issue, please reopen it again.
