### ISSUE TITLE
GTA V freezing on every key press

### ISSUE THREAD

**Issue by TheGreatestJannet** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#7]
Hello, in GTA V wheneven you press the keyboard the whole game freezes until you let go. This makes it unplayable. I haven't tried it outside of flatpak but in the changelog for proton-ge https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.21-GE-1 it stays:
```
HOTFIX 11/18/2020:
Fixed broken key input in GTA V
```
Has this been included in this build?

Thanks!

**Comment by Lctrs** [comment]
Yes. Everything has been included. Have you reproduced the issue with native Steam + upstream Proton-GE build ?

**Comment by TheGreatestJannet** [comment]
No native Steam and upstream Proton-GE doesn't suffer from this issue.

**Comment by TheGreatestJannet** [comment]
This commit might help: https://github.com/GloriousEggroll/proton-ge-custom/commit/56d79401b364927dd7efcc01469fca1c673241a7

**Comment by Lctrs** [comment]
OK so the last commit is present in 5.22-GE-1 but not in 5.21-GE-1. So I'm afraid it's not available in our build.

**Comment by TheGreatestJannet** [comment]
But if you look at the patch notes for the latest release it says it should be in this version as well. Can it not be added?

**Comment by TheGreatestJannet** [comment]
What I think happened is that GloriousEggroll released the hotfix and then pushed the changes to the repo having updated the tag causing it to be tagged against the wrong version.The commit with the patch was pushed a day after the hotfix. This is further confirmed by the fact that the commit that updated wine is the next one after the GTA one.

I guess we will just have to wait for whenever the next release is to get all the hotfixes.
