### ISSUE TITLE
The flathub link (i.e., the link in the about section on github) is broken

### ISSUE THREAD

**Issue by titsuki** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#93]
Hi,
I found that the following link is broken: https://flathub.org/apps/details/com.valvesoftware.Steam.CompatibilityTool.Proton-GE
(Since I'm a Proton-GE newbie, I'm not sure if the link wasn't broken in the past.)

Cheers,

**Comment by Lctrs** [comment]
Expected. Flathub website is not currently capable of displaying flatpak that are extensions and not apps.
